awsdocs/aws-php-developers-guide

doc_source/s3-encryption-client.rst
Made configuration for chiperOptions work
=> Change in 'chipherOptions'

doc_source/guide_configuration.rst
Adds a missing opening square bracket in a snippet of example code. 
=> Add missing opening square bracket

doc_source/emc-examples-getendpoint.rst, doc_source/emc-examples-jobs.rst, doc_source/emc-examples.rst, doc_source/examples_index.rst, doc_source/welcome.rst
Adding articles about Elemental's MediaConvert
=> Media convert

README.rst
=> removing information from ReadMe about v2.

doc_source/guide_credentials.rst, doc_source/guide_credentials_hardcoded.rst
=> Restore hard coded

doc_source/s3-stream-wrapper.rst
*Description of changes:* Fixes a typo in one of the example code snipptes
=> Fix typo in code snipped

doc_source/service_dynamodb-session-handler.rst
None.
Adding a missing word, _do_, to "Basic Usage: Step 2".
=> Adding missing word "do" to Basic Usage, Step 2

doc_source/s3-multipart-upload.rst
=> Adding example for object upload method

doc_source/guide_configuration.rst
=> Endpoint discovery

doc_source/document-history.rst, doc_source/getting-started_basic-usage.rst, doc_source/guide_sdk-metrics-set-permissions.rst, doc_source/kinesis-example-data-stream.rst, doc_source/kinesis-example-shard.rst, doc_source/kinesis-firehose-example-delivery-stream.rst, doc_source/ses-filters.rst, doc_source/ses-rules.rst, doc_source/ses-send-email.rst, doc_source/ses-sender-policy.rst, doc_source/ses-template.rst, doc_source/ses-verify.rst, doc_source/sns-examples-managing-topics.rst, doc_source/sns-examples-sending-sms.rst, doc_source/sns-examples-subscribing-unsubscribing-topics.rst, doc_source/sqs-examples-dead-letter-queues.rst, doc_source/sqs-examples-enable-long-polling.rst, doc_source/sqs-examples-managing-visibility-timeout.rst, doc_source/sqs-examples-send-receive-messages.rst, doc_source/sqs-examples-using-queues.rst
=> Adding references to snippet IDs instead of line numbers

doc_source/examples_index.rst, doc_source/s3-examples-bucket-policies.rst, doc_source/s3-examples-configuring-a-bucket.rst, doc_source/s3-examples-creating-buckets.rst, doc_source/s3-examples-static-web-host.rst, doc_source/s3-examples.rst, doc_source/s3-presigned-post.rst, doc_source/s3-presigned-url.rst, doc_source/service_cloudsearch-custom-requests.rst, doc_source/service_es-data-plane.rst, doc_source/service_index.rst, doc_source/welcome.rst
=> adding code snippets to S3 example articles

doc_source/examples_index.rst, doc_source/secretsmanager-examples-manage-secret.rst
=> Secrets Manager article

doc_source/emc-examples-jobs.rst, doc_source/getting-started_basic-usage.rst, doc_source/getting-started_migration.rst, doc_source/glossary.rst, doc_source/guide_commands.rst, doc_source/guide_configuration.rst, doc_source/guide_credentials.rst, doc_source/guide_credentials_provider.rst, doc_source/guide_paginators.rst, doc_source/guide_streams.rst, doc_source/kinesis-example-shard.rst, doc_source/kms-example-encrypt.rst, doc_source/kms-example-grants.rst, doc_source/kms-example-keys.rst, doc_source/s3-multipart-upload.rst, doc_source/s3-stream-wrapper.rst, doc_source/secretsmanager-examples-manage-secret.rst, doc_source/service_dynamodb-session-handler.rst, doc_source/ses-examples.rst, doc_source/ses-verify.rst, doc_source/sns-examples-subscribing-unsubscribing-topics.rst, doc_source/sqs-examples-enable-long-polling.rst
=> Removing You must 

doc_source/getting-started_migration.rst
https://github.com/aws/aws-sdk-php/issues/1761
Documents v3 SES SendRawEmail base64 encoding of RawMessage in upgrade guide
=> doc SES SendRawEmail base64 handling in upgrade guide

doc_source/guide_credentials_provider.rst
Documents credential_process provider in https://github.com/aws/aws-sdk-php/pull/1764
=> Proccess credentials

doc_source/index.rst
=> Updating the description of the Developer Guide to match documentation hub

doc_source/guide_credentials_assume_role.rst, doc_source/guide_credentials_profiles.rst
=> Adding instructions for Assume Role

doc_source/welcome.rst
=> Adding links to submit feature request to Github. 

.gitignore, doc_source/service_dynamodb-session-handler.rst
Hi guys,
As a result of https://github.com/aws/aws-sdk-php/pull/1784 , I'm opening this PR to update the docs with the latest available attributes to be used within the DynamoDB Session Handler.
Looking forward to your feedback.
Thanks
=> DynamoDB SessionHandler - Configurable data & session lifetime attr

doc_source/guide_credentials_profiles.rst
Documents https://github.com/aws/aws-sdk-php/pull/1804
=> assume role from profile

doc_source/guide_configuration.rst
Add documentation for cert http config option
Documentation for https://github.com/aws/aws-sdk-php/pull/1820
=> Http cert config

.gitignore
=> Add doc_output and venv to .gitignore

doc_source/guide_credentials_profiles.rst
Documents change in https://github.com/aws/aws-sdk-php/pull/1824
=> document loading assume role profiles from config

doc_source/guide_sdk-metrics-configure.rst
* Update SDK metrics documentation with client configuration options, corresponding with [PR-1834](https://github.com/aws/aws-sdk-php/pull/1834) for the PHP SDK.
=> Update SDK metrics with client configuration options

doc_source/service_dynamodb-session-handler.rst
Documents https://github.com/aws/aws-sdk-php/pull/1838
=> doc data_attribute_type on session handler

doc_source/guide_credentials_provider.rst, doc_source/service_dynamodb-session-handler.rst
docs change in https://github.com/aws/aws-sdk-php/pull/1837
=> Instance profile retries

doc_source/service_dynamodb-session-handler.rst
=> Fix minor typo

doc_source/guide_paginators.rst
=> Fix typo in promise code sample

doc_source/rds-examples.rst
=> Amazon RDS examples

doc_source/getting-started_installation.rst
=> adding syntax highlighting for PHP snippets

doc_source/document-history.rst
=> Switching to Sentence Case for Change name

doc_source/s3-stream-wrapper.rst
Fixed misspelling for easier copy/paste
=> Fixed misspelling of 'stream'

doc_source/data-protection.rst
Added note about security vulnerabilities in TLS < 1.2 and link to section about configuring TLS version.
=> Add security note about TLS versions and how to configure

doc_source/s3-examples-access-point-arn.rst, doc_source/s3-examples.rst
* Add a guide for using S3 Access Point ARNs with bucket operations.
=> S3 accesspoint examples

doc_source/guide_credentials_provider.rst
=> Missed comma

doc_source/guide_waiters.rst
=> Added notes on how to find waiter info

doc_source/document-history.rst, doc_source/s3-encryption-client.rst
=> Crypto updates

doc_source/getting-started_requirements.md
=> Change CloudWatch to CloudFront

doc_source/guide_configuration.md
Updates configuration page to include `EndpointProviderV2` as a valid `endpoint_provider` type.
=> Add EndpointProviderV2

doc_source/s3-multipart-upload.md, doc_source/s3-transfer.md
Related to https://github.com/aws/aws-sdk-php/pull/2626
Covers an update to high-level S3 customizations.
=> Enhancement: Update Transfer, ObjectUploader and Multipart config 

doc_source/guide_configuration.md
Tiny typo fix to close single quote correctly.
=> fix typo: close single quote correctly
